# -------------------------------------------------------
# Copyright (c) [2022] Nadege Lemperiere
# All rights reserved
# -------------------------------------------------------
# Analysis pipeline for portal
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 01 march 2022
# -------------------------------------------------------

name: Website Build Pipeline

on: push

jobs:

    build:
        name: Build Website
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Linting code
              uses: docker://node:alpine
              continue-on-error: true
              with:
                args: npm run lint

            - name: Building application
              uses: docker://node:alpine
              with:
                args: npm run build

            - name: Run Snyk to check for vulnerabilities
              continue-on-error: true
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: snyk.sarif

    test:
        name: Testing Website
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Launching tests
              continue-on-error: true
              uses: docker://node:alpine
              with:
                args: npm test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: clover.xml, coverage-final.json,lcov.info
                directory: ./coverage/
                name: codecov-portal
                fail_ci_if_error: true
                verbose: true
                commit_parent: ${{ github.sha }}

    package:
        name: Package Website
        runs-on: ubuntu-latest
        needs: [build, test]
        env:
            dockerhub_user: ${{ secrets.DOCKERHUB_USER }}
            dockerhub_password: ${{ secrets.DOCKERHUB_PASSWORD }}
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Check dockerfile
              continue-on-error: true
              uses: hadolint/hadolint-action@v1.6.0
              with:
                dockerfile: Dockerfile

            - name: Build container
              run: docker image build -t nadegelemperiere/${{ github.event.repository.name }}:${{ github.sha }} .

            - name: Check container
              continue-on-error: true
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'nadegelemperiere/${{ github.event.repository.name }}:${{ github.sha }}'
                format: 'sarif'
                output: trivy.sarif
                exit-code: '0'
                ignore-unfixed: true

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: trivy.sarif

            - name: Login to dockerhub registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

            - name: Publish container
              run: docker image push nadegelemperiere/${{ github.event.repository.name }}:${{ github.sha }}

    publish:
        name: Publish Website
        runs-on: ubuntu-latest
        needs: package
        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                path: portal

            - name: Retrieving vault
              if: ${{ github.ref}} == 'refs/heads/develop'
              uses: actions/checkout@master
              with:
                repository: nadegelemperiere/vault
                path: vault
                ref: v2.1.0
                token: ${{ secrets.GH_ACCESS_TOKEN }}

            - name: Triggering amplify webhook
              if: ${{ github.ref}} == 'refs/heads/develop'
              env:
                VAULT_KEY: ${{ secrets.VAULT_KEY }}
              uses: docker://nadegelemperiere/terraform-python-awscli:v3.0.0
              with:
                args: ./portal/scripts/trigger.sh -b develop -k VAULT_KEY

