# -------------------------------------------------------
# TECHNOGIX
# -------------------------------------------------------
# Copyright (c) [2022] Technogix SARL
# All rights reserved
# -------------------------------------------------------
# Release pipeline for portal
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 01 march 2022
# -------------------------------------------------------

name: Website Pull Request Pipeline

on:
    pull_request:
        types: [ assigned, opened, synchronize, reopened ]

jobs:

    build:
        name: Build Website
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              run: npm install

            - name: Linting code
              run: npm run lint

            - name: Run Snyk to check for vulnerabilities
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: snyk.sarif

    test:
        name: Testing Website
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Launching tests
              continue-on-error: true
              uses: docker://node:alpine
              with:
                args: npm test

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: clover.xml, coverage-final.json,lcov.info
                directory: ./coverage/
                name: codecov-portal
                fail_ci_if_error: true
                verbose: true
                commit_parent: ${{ github.ref_name }}

    package:
        name: Package Website
        runs-on: ubuntu-latest
        needs: [ build, test ]
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Check dockerfile
              uses: hadolint/hadolint-action@v1.6.0
              with:
                dockerfile: Dockerfile

            - name: Build container
              run: docker image build -t technogix/${{ github.event.repository.name }}:${{ github.sha }} .

            - name: Check container
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: 'technogix/${{ github.event.repository.name }}:${{ github.sha }}'
                format: 'sarif'
                output: trivy.sarif
                exit-code: '0'
                ignore-unfixed: true

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: trivy.sarif

            - name: Login to dockerhub registry
              run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

            - name: Publish container
              run: docker image push technogix/${{ github.event.repository.name }}:${{ github.sha }}
