# -------------------------------------------------------
#!/bin/bash
# -------------------------------------------------------
# Copyright (c) [2022] Nadege Lemperiere
# All rights reserved
# -------------------------------------------------------
# Security pipeline for robotframework keywords
# -------------------------------------------------------
# Nadège LEMPERIERE, @01 march 2022
# Latest revision: 01 march 2022
# -------------------------------------------------------

name: Website Regular Scan Pipeline

on:
  schedule:
    - cron:  '0 0 1 * *'
  workflow_dispatch:

jobs:

    sast:
        name: Static Website analysis
        runs-on: ubuntu-latest
        container: node:alpine
        steps:
            - name: Checkout code
              uses: actions/checkout@master

            - name: Installing dependencies
              uses: docker://node:alpine
              with:
                args: npm install

            - name: Linting code
              uses: docker://node:alpine
              continue-on-error: true
              with:
                args: npm run lint

            - name: Building application
              uses: docker://node:alpine
              with:
                args: npm run build

            - name: Run Snyk to check for vulnerabilities
              continue-on-error: true
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
              with:
                args: --sarif-file-output=snyk.sarif

            - name: Upload result to GitHub Code Scanning
              uses: github/codeql-action/upload-sarif@v1
              if: always()
              with:
                sarif_file: snyk.sarif

    dast:
        name: Dynamic Website analysis
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@master
              with:
                path: portal

            - name: Retrieving vault
              uses: actions/checkout@master
              with:
                repository: technogix/vault
                path: vault
                ref: v2.1.0
                token: ${{ secrets.GH_ACCESS_TOKEN }}

            - name: Retrieve testing url
              env:
                VAULT_KEY: ${{ secrets.VAULT_KEY }}
              uses: docker://technogix/terraform-python-awscli:v3.0.0
              with:
                args: ./portal/scripts/url.sh -b develop -k VAULT_KEY

            - name: Reading file content
              id: url
              run: |
                content=`cat url.json`
                echo $content
                echo "::set-output name=url::${content}"

            - name: zap scan
              uses: zaproxy/action-full-scan@v0.3.0
              with:
                token:  ${{ secrets.GH_ACCESS_TOKEN }}
                docker_name: 'owasp/zap2docker-stable'
                target: ${{ fromJSON(steps.url.outputs.url).url }}
                rules_file_name: 'rules.tsv'
                cmd_options: '-a -j'